### ISSUE TITLE
Looking at a Birt crashes my game.

### ISSUE THREAD

**Issue by Pineappleguy03** [N1nn1/species#4]
COOL Ass mod you guys created! Unfortunately for some odd reason. Being Near a Birt causes the game to crash for some unknown reason.
![Untitled](https://github.com/N1nn1/species/assets/83521066/4c2b640f-e52b-4c3a-97bd-71900f6ad11e)

If you need logs! Tell me!

**Comment by Pineappleguy03** [comment]
Ah. Server Error is here. 

[22:27:30] [Netty Epoll Server IO #3/ERROR] [minecraft/PacketEncoder]: Error receiving packet 35
java.lang.ClassCastException: class com.ninni.species.entity.BirtEntity$1 cannot be cast to class net.minecraft.world.level.gameevent.EntityPositionSource (com.ninni.species.entity.BirtEntity$1 is in module species@1.19.2-1.1 of loader 'TRANSFORMER' @659f226a; net.minecraft.world.level.gameevent.EntityPositionSource is in module minecraft@1.19.2 of loader 'TRANSFORMER' @659f226a)
        at net.minecraft.world.level.gameevent.EntityPositionSource$Type.m_142235_(EntityPositionSource.java:82) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
        at net.minecraft.world.level.gameevent.PositionSourceType.m_157874_(PositionSourceType.java:31) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
        at net.minecraft.core.particles.VibrationParticleOption.m_7711_(VibrationParticleOption.java:59) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ClientboundLevelParticlesPacket.m_5779_(ClientboundLevelParticlesPacket.java:65) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at net.minecraft.network.Connection.m_243087_(Connection.java:209) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
        at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar%2385!/:4.1.77.Final] {}
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by XanaDublaKublaConch** [comment]
I had to remove the mod because of this.

**Comment by Pineappleguy03** [comment]
Wait What.

**Comment by Pineappleguy03** [comment]
I forgot to mention. But it is 1.19.... Not 1.20. Unless you just don't work on 1.19 anymore.

**Comment by BugmanBugman** [comment]
Getting this crash as well

**Comment by Sunconure11** [comment]
I haven't seen this crash, but the latest 1.20 builds seem to apparently fix this. I think said fix should be brought over to 1.19.2, as well, just to reduce the number of issues filed about this, so you can continue work on newer builds of MC.

**Comment by Ksieus** [comment]
same issue on fabric 1.19.2 server

**Comment by Fells2** [comment]
I have the same issue

**Comment by ubkh** [comment]
same issue on forge
